In [4]:
#importing dependencies
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt
import time
import mediapipe as mp

Creating KeyPoints MP_HOLISTIC

In [5]:
#create variables for mediapipe
mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils

In [6]:
#create 1st function for mediapipe
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = model.process(image)
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image.flags.writeable = False
    return image, results


In [7]:
#use mediapipe function in opencv feeds
cap = cv2.VideoCapture(1)
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as model:
    while cap.isOpened():
        ret, frame = cap.read()
        image, results = mediapipe_detection(frame, model)
        cv2.imshow('OpenCV Feed', image)
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()


In [8]:
def draw_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             )

In [9]:
#using mediapipe_detection draw_landmarks function in opencv feeds
cap = cv2.VideoCapture(0)
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as model:
    while cap.isOpened():
        ret, frame = cap.read()
        image, results = mediapipe_detection(frame, model)
        draw_landmarks(image, results)
        cv2.imshow('OpenCV Feed', image)
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()

Extract Key Points

In [10]:
print(len(results.face_landmarks.landmark))
print(results.face_landmarks.landmark)
print(len(results.pose_landmarks.landmark))
len(results.left_hand_landmarks.landmark)
    




468
[x: 0.5550521016120911
y: 0.6421179175376892
z: -0.02034003660082817
, x: 0.5525140762329102
y: 0.6031947135925293
z: -0.039635807275772095
, x: 0.5507965087890625
y: 0.6141371130943298
z: -0.020140478387475014
, x: 0.5378127694129944
y: 0.5709608197212219
z: -0.031851887702941895
, x: 0.5512469410896301
y: 0.5927899479866028
z: -0.0425531379878521
, x: 0.5480262637138367
y: 0.5789904594421387
z: -0.03989780694246292
, x: 0.5384443998336792
y: 0.5440763831138611
z: -0.020662156865000725
, x: 0.4743887782096863
y: 0.5583802461624146
z: -0.00046369413030333817
, x: 0.532274067401886
y: 0.5138059854507446
z: -0.016302190721035004
, x: 0.5298965573310852
y: 0.4984731078147888
z: -0.018186047673225403
, x: 0.520734965801239
y: 0.44988757371902466
z: -0.012236423790454865
, x: 0.5557137131690979
y: 0.6474452018737793
z: -0.019063489511609077
, x: 0.5558561682701111
y: 0.6517359018325806
z: -0.016332147642970085
, x: 0.555418074131012
y: 0.6537542343139648
z: -0.012745636515319347
, x: 0.

21

In [11]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks.landmark else np.zeros(132)


In [12]:
print(pose)
pose.shape

[ 5.82153916e-01  5.89409232e-01 -5.84227681e-01  9.99961853e-01
  5.81085026e-01  5.22260010e-01 -5.37182987e-01  9.99920785e-01
  5.87471664e-01  5.19405723e-01 -5.36907256e-01  9.99921441e-01
  5.94287038e-01  5.16619563e-01 -5.36760092e-01  9.99912918e-01
  5.48746288e-01  5.28145671e-01 -5.70966423e-01  9.99937832e-01
  5.29289603e-01  5.31200647e-01 -5.70481777e-01  9.99934614e-01
  5.09536982e-01  5.35975635e-01 -5.70596159e-01  9.99919057e-01
  5.86721063e-01  5.29564679e-01 -2.34281152e-01  9.99934018e-01
  4.67772067e-01  5.58120430e-01 -3.80081981e-01  9.99956131e-01
  5.98734975e-01  6.37923479e-01 -4.65360731e-01  9.99930382e-01
  5.55023313e-01  6.44596279e-01 -5.07773340e-01  9.99956727e-01
  6.82730258e-01  7.53903985e-01 -7.71870986e-02  9.99451518e-01
  3.60447794e-01  8.31676722e-01 -2.33017206e-01  9.97394621e-01
  9.10138011e-01  8.99785340e-01 -3.44000101e-01  9.71310437e-01
  3.73022974e-01  1.23443663e+00 -1.20673299e-01  4.43863511e-01
  7.80217767e-01  5.15247

(132,)

In [13]:
pose.shape

(132,)

In [14]:
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*4)
lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

In [15]:
#function for extracting keypoints
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([pose, face, lh, rh])

In [16]:
result_test = extract_keypoints(results)

In [17]:
result_test.shape

(1662,)

In [18]:
result_test

array([ 0.58215392,  0.58940923, -0.58422768, ...,  0.        ,
        0.        ,  0.        ])

In [21]:
DATA_PATH = os.path.join('MP_Data') 
actions = np.array(['hello', 'thanks', 'iloveyou'])
no_sequences = 30
sequence_length = 30

In [21]:
for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

In [22]:
#using mediapipe_detection draw_landmarks function in opencv feeds
cap = cv2.VideoCapture(0)
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as model:
    for action in actions:
        for sequence in range(no_sequences):
            for frame_num in range(sequence_length):
                ret, frame = cap.read()
                image, results = mediapipe_detection(frame, model)
                draw_landmarks(image, results)
                
                if frame_num == 0:
                    cv2.putText(image, 'starting collection', (120, 200), 
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 4, cv2.LINE_AA)

                    cv2.putText(image, 'collecting frames for {} video number{}'.format(action, sequence), (15, 12),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 4, cv2.LINE_AA)

                    cv2.waitKey(500)

                else:
                    cv2.putText(image, 'collecting frames for {} video number{}'.format(action, sequence), (15, 12),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 4, cv2.LINE_AA)    

                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))    
                np.save(npy_path, keypoints)

                cv2.imshow('OpenCV Feed', image)
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break

cap.release()
cv2.destroyAllWindows()

In [22]:
label_map = {'hello': 0, 'thanks': 1, 'iloveyou': 2}
label_map

{'hello': 0, 'thanks': 1, 'iloveyou': 2}

In [23]:
sequences, labels = [], []
for action in actions:
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequence_length):
            
            res =  np.load(os.path.join(DATA_PATH, action, str(sequence), '{}.npy'.format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [24]:
labels

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [25]:
np.array(sequences).shape


(90, 30, 1662)

In [26]:
np.array(labels).shape

(90,)

In [27]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical


In [28]:
x = np.array(sequences)
y = to_categorical(labels).astype(int)

In [29]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [30]:
x

array([[[ 0.53726774,  0.61049461, -0.61498922, ...,  0.        ,
          0.        ,  0.        ],
        [ 0.54437214,  0.61255985, -0.58813274, ...,  0.        ,
          0.        ,  0.        ],
        [ 0.55315059,  0.61294138, -0.58959508, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.5688566 ,  0.56717813, -0.61203039, ...,  0.24393383,
          0.32617205, -0.01151416],
        [ 0.56843287,  0.56834823, -0.62186176, ...,  0.23621726,
          0.33446598, -0.01460908],
        [ 0.56781775,  0.56850201, -0.69872022, ...,  0.2302855 ,
          0.34916097, -0.01292336]],

       [[ 0.56854254,  0.56806189, -0.62884849, ...,  0.22869411,
          0.35270432, -0.0083457 ],
        [ 0.56837875,  0.56707501, -0.6407662 , ...,  0.22861171,
          0.33769938, -0.01621867],
        [ 0.56771058,  0.56617433, -0.60354775, ...,  0.21258108,
          0.32423174, -0.02233068],
        ...,
        [ 0.58086652,  0.56772846, -0.69758809, ...,  

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05)

In [32]:
x_train.shape

(85, 30, 1662)

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.callbacks import TensorBoard

In [34]:
log_dir = os.path.join('logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [35]:
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30, 1662)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(256, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 30, 64)            442112    
_________________________________________________________________
lstm_4 (LSTM)                (None, 30, 128)           98816     
_________________________________________________________________
lstm_5 (LSTM)                (None, 256)               394240    
_________________________________________________________________
dense_2 (Dense)              (None, 64)                16448     
_________________________________________________________________
dense_3 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 99        
Total params: 953,795
Trainable params: 953,795
Non-trainable params: 0
________________________________________________

In [38]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=150, callbacks=[tb_callback])

Train on 85 samples
Epoch 1/150
85/85 [==============================] - 3s 30ms/sample - loss: 1.7002 - accuracy: 0.6000
Epoch 2/150
85/85 [==============================] - 0s 3ms/sample - loss: 1.4395 - accuracy: 0.5412
Epoch 3/150
85/85 [==============================] - 0s 3ms/sample - loss: 6.7304 - accuracy: 0.2824
Epoch 4/150
85/85 [==============================] - 0s 3ms/sample - loss: 1.7795 - accuracy: 0.3529
Epoch 5/150
85/85 [==============================] - 0s 3ms/sample - loss: 1.2313 - accuracy: 0.5647
Epoch 6/150
85/85 [==============================] - 0s 3ms/sample - loss: 1.1652 - accuracy: 0.5882
Epoch 7/150
85/85 [==============================] - 0s 3ms/sample - loss: 0.9094 - accuracy: 0.6588
Epoch 8/150
85/85 [==============================] - 0s 3ms/sample - loss: 0.6832 - accuracy: 0.8235
Epoch 9/150
85/85 [==============================] - 0s 3ms/sample - loss: 1.0835 - accuracy: 0.5412
Epoch 10/150
85/85 [==============================] - 0s 4ms/sample - 